/*
 * Copyright (C) 2016-2025 Yuriy Yarosh
 * All rights reserved.
 *
 * SPDX-License-Identifier: MPL-2.0
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

use derive_more::*;

use serde::*;

#[derive(derive_more::Debug, Clone, PartialEq, Display, Serialize, Deserialize)]
pub enum Tag {
    #[display("a")]
    A,
    #[display("abbr")]
    Abbr,
    #[display("address")]
    Address,
    #[display("area")]
    Area,
    #[display("article")]
    Article,
    #[display("aside")]
    Aside,
    #[display("audio")]
    Audio,
    #[display("b")]
    B,
    #[display("base")]
    Base,
    #[display("bdi")]
    BDI,
    #[display("bdo")]
    BDO,
    #[display("blockquote")]
    BlockQuote,
    #[display("body")]
    Body,
    #[display("br")]
    Br,
    #[display("button")]
    Button,
    #[display("canvas")]
    Canvas,
    #[display("caption")]
    Caption,
    #[display("cite")]
    Cite,
    #[display("code")]
    Code,
    #[display("col")]
    Col,
    #[display("colgroup")]
    ColGroup,
    #[display("data")]
    Data,
    #[display("datalist")]
    DataList,
    #[display("dd")]
    DD,
    #[display("del")]
    Del,
    #[display("details")]
    Details,
    #[display("dfn")]
    Dfn,
    #[display("dialog")]
    Dialog,
    #[display("div")]
    Div,
    #[display("dl")]
    Dl,
    #[display("dt")]
    Dt,
    #[display("em")]
    Em,
    #[display("embed")]
    Embed,
    #[display("fieldset")]
    FieldSet,
    #[display("figcaption")]
    FigCaption,
    #[display("figure")]
    Figure,
    #[display("footer")]
    Footer,
    #[display("form")]
    Form,
    #[display("head")]
    Head,
    #[display("header")]
    Header,
    #[display("hgroup")]
    HGroup,
    #[display("h1")]
    H1,
    #[display("h2")]
    H2,
    #[display("h3")]
    H3,
    #[display("h4")]
    H4,
    #[display("h5")]
    H5,
    #[display("h6")]
    H6,
    #[display("hr")]
    HR,
    #[display("html")]
    Html,
    #[display("i")]
    I,
    #[display("iframe")]
    IFrame,
    #[display("img")]
    Img,
    #[display("input")]
    Input,
    #[display("ins")]
    Ins,
    #[display("kbd")]
    Kbd,
    #[display("keygen")]
    Keygen,
    #[display("label")]
    Label,
    #[display("legend")]
    Legend,
    #[display("li")]
    Li,
    #[display("link")]
    Link,
    #[display("main")]
    Main,
    #[display("map")]
    Map,
    #[display("mark")]
    Mark,
    #[display("menu")]
    Menu,
    #[display("menuitem")]
    MenuItem,
    #[display("meta")]
    Meta,
    #[display("meter")]
    Meter,
    #[display("nav")]
    Nav,
    #[display("noscript")]
    NoScript,
    #[display("object")]
    Object,
    #[display("ol")]
    Ol,
    #[display("optgroup")]
    OptGroup,
    #[display("option")]
    Option,
    #[display("output")]
    Output,
    #[display("p")]
    P,
    #[display("rp")]
    RP,
    #[display("rt")]
    RT,
    #[display("ruby")]
    Ruby,
    #[display("s")]
    S,
    #[display("samp")]
    Samp,
    #[display("script")]
    Script,
    #[display("selection")]
    Selection,
    #[display("select")]
    Select,
    #[display("small")]
    Small,
    #[display("source")]
    Source,
    #[display("span")]
    Span,
    #[display("strong")]
    Strong,
    #[display("style")]
    Style,
    #[display("sub")]
    Sub,
    #[display("summary")]
    Summary,
    #[display("sup")]
    Sup,
    #[display("svg")]
    Svg,
    #[display("table")]
    Table,
    #[display("tbody")]
    TBody,
    #[display("td")]
    Td,
    #[display("template")]
    Template,
    #[display("textarea")]
    TextArea,
    #[display("tfoot")]
    TFoot,
    #[display("th")]
    Th,
    #[display("thead")]
    THead,
    #[display("time")]
    Time,
    #[display("title")]
    Title,
    #[display("tr")]
    Tr,
    #[display("track")]
    Track,
    #[display("u")]
    U,
    #[display("ul")]
    Ul,
    #[display("var")]
    Var,
    #[display("video")]
    Video,
    #[display("wbr")]
    Wbr,
    #[display("{_0}")]
    Custom(String),
}
